# Generated by Django 5.2.8 on 2025-11-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sustainability_score', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('badges', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
